### PR TITLE
SU-343 : Evidencias Sprint 14-15 (12) / Reporte de recaudo de seguros

### PR DESCRIPTION
**Pull request by tabrez-fiter**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by francofiter — DISMISSED** [review]
@tabrez-fiter Checking this change I noticed that the change was expected to be for the report of "Recaudos de Seguros Obligatorios" however in the condition I see: 

" <where> report_name='Novedades de Seguros Obligatorios' </where>"

So once again it would have broken another report different from the expected one.

**Review by fiter-julius-oketayot — APPROVED** [review]

**Comment by faheem205** [comment]
@tabrez-fiter spotleas errors in PR

**Review by francofiter — COMMENTED** [review]
Please note that the LIQUIDACION DE COBROS is not the same that the expected

"ccapos.code AS "ID del Punto de Venta","
should be:
“ccapos.code AS "Código del Punto de Venta", "

**Comment by tabrez-fiter** [comment]
fixed the where condition for report 'Recaudos de Seguros Obligatorios' and for Código del Punto de Venta for report cobros

**Review by fiter-julius-oketayot — APPROVED** [review]

**Pull request merged**
